# vim: set ft=yaml:

# when provide certficate file, server will listen https and enable http2
listen:
  -
    addr: 0.0.0.0
    port: 9001
    certificates:
  -
    addr: 0.0.0.0
    port: 9002
    certificates:
      -
        certfile: /etc/letsencrypt/live/ratafee.nl/fullchain.pem
        keyfile: /etc/letsencrypt/live/ratafee.nl/privkey.pem

# virtual host support
vhost:
  -
    hostname: www.ratafee.nl
    docroot: /srv/www
    proxypass: http://nginx:80/
proxy:
  http1-proxy: false
  http2-proxy: true
  # trust the follow domains as local virtual host
  # when http2 proxy enabled
  localdomains:
    - localhost
    - localdomain
    - 127.0.0.1
    - ratafee.nl
    - 98.142.138.194
